language: python
python:
  - "2.7"
before_install:
  - wget -O miniconda.sh https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda2/bin:$PATH
  - conda update --yes conda
# command to install dependencies
install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION atlas numpy scipy flake8
  - conda install --yes -c tlatorre pygame=1.9.2
  - conda install --yes -c ska pygtk=2.16.0
  - pip install python-coveralls nose-cov unittest2 flake8-pep257
  - bash -c 'if [ "$TRAVIS_PYTHON_VERSION" == "2.7" ]; then pip install functools32; fi'
  - pip install https://github.com/infant-cognition-tampere/drop/archive/develop.zip
  - pip install -e .
# command to run tests
script:
  - nosetests --with-cov --cov drop --cov-config .coveragerc --logging-level=INFO

after_success:
  - coveralls --config_file .coveragerc

# TODO: Setup Slack
# notifications:
#   slack:
#     secure:
